### ISSUE TITLE
Proposed changes to r2dii_*_colours()

### ISSUE THREAD

**Issue by maurolepore** [2DegreesInvesting/r2dii.plot.static#108]
Relates to #95

The funciton `2dii_*_colours()` output a dataframe.
This is similar to what get_example_data() does, yet 
lacks the prefix `get_`. This inconsistenty doesn't 
help users transfer the knowledge they gain from one
function to another. 

Instead we may either use a name like `get_2dii_*_colours()`
(if get_example_data() survives) or more simply add
the output dataframe to data/ with usethis::use_data()
then let user access it directly with `2dii_*_colours`.

**Comment by MonikaFu** [comment]
I think that issue #22 is also relevant here. Maybe instead of functions returning data frames with colours we should use the colour palette as suggested there?

**Comment by maurolepore** [comment]
Closing in favor of #144
