### ISSUE TITLE
In plot_*() the argument plot_title could be called just title

### ISSUE THREAD

**Issue by maurolepore** [2DegreesInvesting/r2dii.plot.static#113]
In a function prefixed with plot_ the prefix plot_ in plot_title 
seems redundant.

**Comment by MonikaFu** [comment]
I think that we are going to pull all titles out of the plotting functions so this issue will become obsolete then? Should we just create another issue for it and close this one?

**Comment by MonikaFu** [comment]
Closing this issue as it is covered in #123
