### ISSUE TITLE
Rename arguments to match their corresponding name in ggplot2

### ISSUE THREAD

**Issue by maurolepore** [2DegreesInvesting/r2dii.plot.static#117]
As a user of the most popular visualization package
ggplot2 I would like this package to have arguments
named so that I can reuse here the knowlege I bring
from ggplot2. 

For example, I know that to change the label of the
x axis I can use ggplot2::xlab(). Then I would
prefer to see here an argument called 'xlab' rather
than 'x_title' -- it the value is passed to 
ggplot2::xlab().

**Comment by MonikaFu** [comment]
I think that we are going to pull all titles out of the plotting functions so this issue will become obsolete then? Should we just create another issue for it and close this one?

**Comment by maurolepore** [comment]
Yeah, I think that's a good idea so we reduce the number of open issues.

**Comment by MonikaFu** [comment]
Closing this issue because it is covered in #123
