### ISSUE TITLE
suggestions for prepare_for_timeline()

### ISSUE THREAD

**Issue by cjyetman** [2DegreesInvesting/r2dii.plot.static#145]
I was trying to use `prepare_for_timeline()` with investor data. Here are a few things I noticed/desired...

1. The `sector_filter` argument allows one to explicitly list the sectors they want, but I would like a way to specify *all* sectors without having to the each one out.
2. The `sector_filter` argument matches a set of sector names that do not exist in invest data (e.g. investor data has `Aviation` not `aviation`), so it's impossible to use without modifying all the sector names in my data to match these.
3. It would be nice to be able to specify the column that the sectors are defined by, rather than being required to modify that column name in my data before passing to `prepare_for_timeline()`

**Comment by cjyetman** [comment]
Also, there's no `Coal` sector?

**Comment by cjyetman** [comment]
So, now I understand that the `sector_filter` argument is meant to select only one sector at a time, so point 1. above is irrelevant. I was confused because the help file says "sector_filter | Sector to be used for filtering (character string or a vector of character strings)", which I took to mean that it would accept a vector of sector names.

**Comment by cjyetman** [comment]
also, it's not super clear that if you do not specify `sector_filter`, as in the example in the `plot_timeline()` help page, then `automotive` is chosen by default

```library(ggplot2)

data <- sda_target

# You may prepare and plot an sda_target-like dataset using defaults
data %>%
  prepare_for_timeline() %>%
  plot_timeline()
```

**Comment by MonikaFu** [comment]
Thanks @cjyetman for your feedback. In principle I did not adjust the code of the plots yet to be usable for investor output (see #24 ) as banks' have priority for the CRAN release and as I don't have test data for investors output. But I guess that @maurolepore has already tried to solve some of the issues that you mention so maybe at least this chart will be usable for investors in this release. 

We should definitely adjust the parameters description for 'sector_filter'. First for catching that!
