### ISSUE TITLE
Bonds and Equities should have colours that are closer in intensity

### ISSUE THREAD

**Issue by MonikaFu** [2DegreesInvesting/r2dii.plot.static#32]
Consider changing the currently used 'Bonds' colour to one that is not differing in intensity from 'Equity' colour. Currently the colour choice might be indicating that 'Bonds' are more important. 

Currently:
![image](https://user-images.githubusercontent.com/26434113/106280712-8abbf400-623e-11eb-999a-8bb77f5d143c.png)

Consider changing 'Bonds' to 'moss_green' from 2DII palette:
![image](https://user-images.githubusercontent.com/26434113/106280750-9c050080-623e-11eb-96ba-58b68dac1468.png)

@cjyetman @jdhoffa @fiona511 any opinions?

**Comment by cjyetman** [comment]
I don't know if they were actually designed/chosen scientifically, but the "secondary palette" in the 2dii official design spec is supposedly intended "for info graphics only", and to my eye they look like they may be more appropriate for unordered categorical data.
 
`#a63d57` Ruby red 
`#f2e06e` Yellow
`#78c4d6` Soft blue
`#574099` Dark purple
`#4a5e54` Moss green

**Comment by MonikaFu** [comment]
I don't think that they were designed 'scientifically'. For example, the yellow is a bit too bright compared to the others. If the colours differ too much - it might suggest a significant difference that is not present in the data. Since Equity and Bonds are equally 'important' they should also have colours of equal 'brightness', or 'vividness' (I'm not sure what the right term for this concept is in English). What I mean is that currently the 'green' of Bonds is much more eye-catching than 'dark_blue' of equity suggesting that the viewer should pay more attention to it.

**Comment by cjyetman** [comment]
Yes, I agree with you on the contrast/difference in intensity/brightness/vividness/whatever between the Dark blue and Green. To my eyes, that contrast/difference is less pronounced between the "secondary palette" colors.

I would also support developing, proposing, and advocating for a scientifically designed palette to be added to the official 2dii  design spec if the current one is not adequate. It would probably make sense to have an unordered and an ordered palette.

I'm less excited about the idea of arbitrarily choosing a new set of colors for this unique situation.

**Comment by MonikaFu** [comment]
Moved to [`r2dii.plot.internal`](https://github.com/2DegreesInvesting/r2dii.plot.internal/issues/4)
