### ISSUE TITLE
Split off meta report from this repo

### ISSUE THREAD

**Issue by MonikaFu** [2DegreesInvesting/r2dii.plot.static#60]
We might want to put the meta report charts in another (related) repo so that the banks-related charts can be CRAN-ready and released without waiting for test datasets to be developed. These charts are only to be used internally so it might be a good idea to separate them from this repo but link somehow.

@maurolepore - happy to hear your thoughts. 

It might be an important step to be performed before #43

**Comment by maurolepore** [comment]
Let's chat next time we meet.
