### ISSUE TITLE
Change the name of the package

### ISSUE THREAD

**Issue by MonikaFu** [2DegreesInvesting/r2dii.plot.static#65]
Required for #43 

Following the discussion with @maurolepore - if we want to publish on CRAN it might be good idea to change the name of the package from 'ggplot' to something else. I had good reasons for naming it this way internally (clear indication that the output plots are ggplot objects) but it might better not to publish under this name as it might look as if we are trying to confuse the users or 'use' ggplot fame to promote our package. To make users aware of 'ggplot' relation of this package, I can indicate it in the description and in the examples. 

Any suggestions for a better name? @cjyetman @maurolepore @jdhoffa @AlexAxthelm @jacobvjk @georgeharris2deg ?

I was thinking of:
* `r2dii.plots`
* `r2dii.plotting`
* `r2dii.static.plots`

Following #60 - this name will only concern the plots related to `r2dii.analysis` output (banks' format). The metareport (and potentially other) charts will leave in a different, but related package (for example: `r2dii.plotting.internal`).

**Comment by AlexAxthelm** [comment]
I would add a vote for `r2dii.static.plots`, to distinguish it from interactive plots that we'll be doing.

**Comment by cjyetman** [comment]
I missed the reasoning for having multiple packages/repos that do plotting? I could even imagine combining the interactive plotting tools with the static plotting tools all into one.

**Comment by maurolepore** [comment]
👍 r2dii.static.plots or r2dii.static.plot — if another interactive package is clearly in the horizon.  If not, just r2dii.plot should do. 

The pooling of packages that CJ suggests is something to consider — although a similar effect we could achieve with the meta package ‘r2dii’.

**Comment by maurolepore** [comment]
BTW  https://www.njtierney.com/post/2017/10/27/change-pkg-name/

![image](https://user-images.githubusercontent.com/5856545/113758872-4418c900-96c9-11eb-87a9-be443bd8512a.png)

**Comment by jdhoffa** [comment]
+1 for `r2dii.static.plots`
+1 for combining both packages

Will let people with more context decide!

**Comment by AlexAxthelm** [comment]
Is there a compelling reason to combine them? the interactive stuff is mostly JS based, right? That might be pretty daunting for newer contributors.

I generally prefer smaller, but numerous packages, if they are independent, sot hat they can be versioned and managed separately. Do one thing, but do it well.

**Comment by cjyetman** [comment]
Well, that we're debating how to name this package, and probably part of it is cautiously doing so while leaving space for reasonable names for other future packages that will do very similar things (e.g. r2dii.static.plots, r2dii.interactive.plots, r2dii.static.plots.for.meta.reports, r2dii.interactive.plots.for.meta.reports, r2dii.static.plots.for.investors, etc.)... that suggests combining the functionality to me. From a user perspective, I think it's easier to have one "go to" plotting package then have to figure out which one has the stuff you want every time you go to use it. From a developers perspective, I think it's pretty normal to work on a repo where you don't fully understand how parts of it work, you just don't mess with the interactive/JS plotting stuff if you don't understand it.

**Comment by AlexAxthelm** [comment]
If the collective wants to unify the packages, I'm okay with that. I don't have a strong opinion.

**Comment by MonikaFu** [comment]
Thanks for all the contributions! I think that I would still separate them but maybe then use the umbrella idea from `r2dii` if users want to install all of them in one go? So have a meta-package `r2dii.plot` which would install all the plotting packages? And have separate packages named sth like: `r2dii.plot.interactive`, `r2dii.plot.static` etc?

**Comment by maurolepore** [comment]
Done. For backward compatibility the old package continues to exist at https://github.com/2DegreesInvesting/r2dii.ggplot, however, the old issues remain here, at https://github.com/2DegreesInvesting/r2dii.plot.static.
