### ISSUE TITLE
Prune dependencies

### ISSUE THREAD

**Issue by MonikaFu** [2DegreesInvesting/r2dii.plot.static#78]
Before releasing to CRAN we should get rid of as many dependencies as possible.

It is possible that we can already get rid of quite a few because of the moving of metareport functions into `r2dii.plot.internal` package.

**Comment by maurolepore** [comment]
Info about problematic dependencies (thanks @cjyetman):

https://github.com/2DegreesInvesting/r2dii.plot.static/pull/34#issuecomment-770754983
https://github.com/2DegreesInvesting/r2dii.plot.static/pull/34#issuecomment-770763235
