### ISSUE TITLE
Do we use the folder colors/?

### ISSUE THREAD

**Issue by maurolepore** [2DegreesInvesting/r2dii.plot.static#82]
https://github.com/2DegreesInvesting/r2dii.plot.static/tree/master/colors

**Comment by MonikaFu** [comment]
Indeed, not anymore. I kept it for reference where the colours in the functions are coming from. And was considering maybe reading colours from the .csv at some point but I don't know if it is a good idea. If I manage to create colour scales (#28)

**Comment by maurolepore** [comment]
Closed by #22
