### ISSUE TITLE
Move example data to data/ (i.e. call `use_data(df)` from data-raw/df.R)

### ISSUE THREAD

**Issue by maurolepore** [2DegreesInvesting/r2dii.plot.static#95]
The readr package has a similar but more flexible feature:

``` r
# List all available example datasets
readr::readr_example()
#> [1] "challenge.csv"     "epa78.txt"         "example.log"      
#> [4] "fwf-sample.txt"    "massey-rating.txt" "mtcars.csv"       
#> [7] "mtcars.csv.bz2"    "mtcars.csv.zip"

# Output not a data frame but a path to the dataset
readr::readr_example("challenge.csv")
#> [1] "/home/mauro/R/x86_64-pc-linux-gnu-library/4.0/readr/extdata/challenge.csv"
```

<sup>Created on 2021-04-22 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

**Comment by maurolepore** [comment]
I notice that also `process_input_data()` needs to be more flexible. Once this package grows we'll likely have multiple example datasets, and each may need to be processed in a particular way.

**Comment by maurolepore** [comment]
@AlexAxthelm what's your opinion?

The enhancement I suggest here would give the package room to grow, but it could also be seen as YAGNI (You Aren't Gonna Need It).

**Comment by cjyetman** [comment]
@maurolepore it might help to explain what is the current behavior of `get_example_data()`, because I don't know what that is off-hand, so I assume @AlexAxthelm won't know either.

**Comment by AlexAxthelm** [comment]
Let's do this once we've got another example dataset to show.

**Comment by maurolepore** [comment]
It looks like we already do. @MonikaFu can you confirm that both `get_example_data()` and `sda_target` output example datasets?

![image](https://user-images.githubusercontent.com/5856545/115884226-46db2400-a414-11eb-84f0-cf1156e50964.png)


--

![image](https://user-images.githubusercontent.com/5856545/115884007-0bd8f080-a414-11eb-9084-2607bb49e1c0.png)

**Comment by AlexAxthelm** [comment]
Okay. This looks like it will involve altering some tests, as well.

And as a suggestion, I'd offer more than just a list when called without args. Maybe something along the lines of:

```r
get_example_data()
#> Call this function again with the name of an example dataset to retrieve that data:
#> 
#> get_example_data("banks")
#> 
#> [1] "banks"     "sda_target"
```

and the function should return the dataset, not a path. If you want to return a path, I'd make a function with a different name (maybe `example_data_path()`), which might be useful for demonstrating loading a file.

**Comment by maurolepore** [comment]
Here I try to summarize this thread. 

Assuming we do have more than one examample dataset, and 
based on the conversation here I see three options:

1. Make all example datasets available directly, e.g. 
   with something like `sda_target`, by adding them all
   into data/ via `usethis::use_data()`.

2. Install all example datasets install with the
   package by adidng them as text files in inst/extdata
   then:

       2.1. export a helper like readr::readr_example()﻿
            which shows all available datasets when called
            with no argument and outputs a path when
            called with a strings naming the dataset.

       2.2. export a helper that shows all available
            datasets when called with no argument, and
            outputs the dataset when called with a
            string naming the dataset. 

The name of the exported helper would depend on which
option we choose. 

@MonikaFu, please confirm we do have more than one
example and discuss which option you think is more
appropriate.

**Comment by MonikaFu** [comment]
I confirm that at the moment we have 2 example datasets. It might be a good idea indeed to have one function calling them with different arguments. I like option 2.2 the most

**Comment by maurolepore** [comment]
@AlexAxthelm do you have any example of a package in the wild using the approach listed as 2.2?

I know many of 1.1 (eg babynames) and 2.1 (eg readr) but not 2.2.

**Comment by cjyetman** [comment]
`readr::readr_example()` is intended to show example **files** included in the package, not examples **datasets**, in which case it makes sense that it would return a filepath...
``` r
readr::readr_example()
#> [1] "challenge.csv"     "epa78.txt"         "example.log"      
#> [4] "fwf-sample.txt"    "massey-rating.txt" "mtcars.csv"       
#> [7] "mtcars.csv.bz2"    "mtcars.csv.zip"
```

@maurolepore do you know of any packages that have a `readr::readr_example()` style function that is intended for a list of example **datasets** included in the package. I am not, so I'm more familiar with the 1. solution (e.g. `dplyr`'s example datasets)

**Comment by AlexAxthelm** [comment]
@maurolepore I don't. That's probably because I forgot that R allows lazy loading of datasets. 🤦 

I'd vote for Option 1, since that's in line with the community practice.

**Comment by MonikaFu** [comment]
I'm also fine with option 1 if that is community practice

**Comment by maurolepore** [comment]
@cjyetman, not sure if I'm answering your exact question but here is my attempt:

`data()` gets close to listing all datasets in a package -- for example, `data(package = "dplyr")` gives a nice html-like output but the underlying object is hard to program with:

``` r
unclass(data(package = "dplyr"))
#> $title
#> [1] "Data sets"
#> 
#> $header
#> NULL
#> 
#> $results
#>      Package LibPath                                        
#> [1,] "dplyr" "/home/mauro/R/x86_64-pc-linux-gnu-library/4.0"
#> [2,] "dplyr" "/home/mauro/R/x86_64-pc-linux-gnu-library/4.0"
#> [3,] "dplyr" "/home/mauro/R/x86_64-pc-linux-gnu-library/4.0"
#> [4,] "dplyr" "/home/mauro/R/x86_64-pc-linux-gnu-library/4.0"
#> [5,] "dplyr" "/home/mauro/R/x86_64-pc-linux-gnu-library/4.0"
#>      Item                Title                
#> [1,] "band_instruments"  "Band membership"    
#> [2,] "band_instruments2" "Band membership"    
#> [3,] "band_members"      "Band membership"    
#> [4,] "starwars"          "Starwars characters"
#> [5,] "storms"            "Storm tracks data"  
#> 
#> $footer
#> NULL
```

To create a list from all datasets, you need significant gymnastics and I don’t know of any CRAN package that does it. So we built our own internally:

``` r
r2dii.data:::exported_data(package = "dplyr")
#> [1] "band_instruments"  "band_instruments2" "band_members"     
#> [4] "starwars"          "storms"

library(dplyr)
#> 
#> Attaching package: 'dplyr'
#> The following objects are masked from 'package:stats':
#> 
#>     filter, lag
#> The following objects are masked from 'package:base':
#> 
#>     intersect, setdiff, setequal, union
r2dii.data:::enlist_datasets(package = "dplyr")
#> $band_instruments
#> # A tibble: 3 x 2
#>   name  plays 
#>   <chr> <chr> 
#> 1 John  guitar
#> 2 Paul  bass  
#> 3 Keith guitar
#> 
#> $band_instruments2
#> # A tibble: 3 x 2
#>   artist plays 
#>   <chr>  <chr> 
#> 1 John   guitar
#> 2 Paul   bass  
#> 3 Keith  guitar
#> 
#> $band_members
#> # A tibble: 3 x 2
#>   name  band   
#>   <chr> <chr>  
#> 1 Mick  Stones 
#> 2 John  Beatles
#> 3 Paul  Beatles
#> 
#> $starwars
#> # A tibble: 87 x 14
#>    name    height  mass hair_color  skin_color eye_color birth_year sex   gender
#>    <chr>    <int> <dbl> <chr>       <chr>      <chr>          <dbl> <chr> <chr> 
#>  1 Luke S…    172    77 blond       fair       blue            19   male  mascu…
#>  2 C-3PO      167    75 <NA>        gold       yellow         112   none  mascu…
#>  3 R2-D2       96    32 <NA>        white, bl… red             33   none  mascu…
#>  4 Darth …    202   136 none        white      yellow          41.9 male  mascu…
#>  5 Leia O…    150    49 brown       light      brown           19   fema… femin…
#>  6 Owen L…    178   120 brown, grey light      blue            52   male  mascu…
#>  7 Beru W…    165    75 brown       light      blue            47   fema… femin…
#>  8 R5-D4       97    32 <NA>        white, red red             NA   none  mascu…
#>  9 Biggs …    183    84 black       light      brown           24   male  mascu…
#> 10 Obi-Wa…    182    77 auburn, wh… fair       blue-gray       57   male  mascu…
#> # … with 77 more rows, and 5 more variables: homeworld <chr>, species <chr>,
#> #   films <list>, vehicles <list>, starships <list>
#> 
#> $storms
#> # A tibble: 10,010 x 13
#>    name   year month   day  hour   lat  long status      category  wind pressure
#>    <chr> <dbl> <dbl> <int> <dbl> <dbl> <dbl> <chr>       <ord>    <int>    <int>
#>  1 Amy    1975     6    27     0  27.5 -79   tropical d… -1          25     1013
#>  2 Amy    1975     6    27     6  28.5 -79   tropical d… -1          25     1013
#>  3 Amy    1975     6    27    12  29.5 -79   tropical d… -1          25     1013
#>  4 Amy    1975     6    27    18  30.5 -79   tropical d… -1          25     1013
#>  5 Amy    1975     6    28     0  31.5 -78.8 tropical d… -1          25     1012
#>  6 Amy    1975     6    28     6  32.4 -78.7 tropical d… -1          25     1012
#>  7 Amy    1975     6    28    12  33.3 -78   tropical d… -1          25     1011
#>  8 Amy    1975     6    28    18  34   -77   tropical d… -1          30     1006
#>  9 Amy    1975     6    29     0  34.4 -75.8 tropical s… 0           35     1004
#> 10 Amy    1975     6    29     6  34   -74.8 tropical s… 0           40     1002
#> # … with 10,000 more rows, and 2 more variables: ts_diameter <dbl>,
#> #   hu_diameter <dbl>
```

<sup>Created on 2021-04-27 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

**Comment by cjyetman** [comment]
no, I was just wondering if you know of a package that has a function that works like this...

``` r
mypkg::example_data()
#> [1] "ex_datatset1"     "ex_datatset2"         "ex_datatset3"      

mypkg::example_data("ex_datatset1")
[1] "/Users/cj2dii/Library/R/4.0/library/mypkg/extdata/ex_datatset1.rds"

mypkg::example_data("ex_datatset2")
[1] "/Users/cj2dii/Library/R/4.0/library/mypkg/extdata/ex_datatset2.rds"
```

I've never seen that before, and that wouldn't seem very useful to me, but as I understand the options, that's what 2.1 would be.

**Comment by AlexAxthelm** [comment]
Is there value in having datasets as raw files (`csv`, `xlsx`, etc.) and having vignettes walk through the entire process, import to results, or would that be best covered in `data_processing`?

**Comment by maurolepore** [comment]
@cjyetman,

> no, I was just wondering if you know of a package that has a function that works like this... `mypkg::example_data()` ...

As Alex pointed before, if a package needs to show how to read data, then
it’s convenient to store raw data in int/extdata then use
`system.file()` or a wrapper (e.g. `pkg_example()`) to read it from the
package installation folder.

For example, readr and vroom do that, and likely other pakcages that follow
The guideline is documented in “R packages”:
&gt; If you want to store raw data, put it in inst/extdata
&gt; –<https://r-pkgs.org/data.html>

And its implemented in readr (earlier) and vroom (later)

``` r
readr::readr_example()
#> [1] "challenge.csv"     "epa78.txt"         "example.log"      
#> [4] "fwf-sample.txt"    "massey-rating.txt" "mtcars.csv"       
#> [7] "mtcars.csv.bz2"    "mtcars.csv.zip"
readr::readr_example("mtcars.csv")
#> [1] "/home/mauro/R/x86_64-pc-linux-gnu-library/4.0/readr/extdata/mtcars.csv"

# vroom's design follows best practices more closely: 1 function for 1 thing
vroom::vroom_examples()
#> [1] "fwf-sample.txt" "mtcars-4.csv"   "mtcars-6.csv"   "mtcars-8.csv"  
#> [5] "mtcars.csv"     "mtcars.csv.bz2" "mtcars.csv.gz"  "mtcars.csv.xz" 
#> [9] "mtcars.csv.zip"
vroom::vroom_example("mtcars.csv")
#> [1] "/home/mauro/R/x86_64-pc-linux-gnu-library/4.0/vroom/extdata/mtcars.csv"
```

Examples in wild: I remember mine, but likely others follow the same lead

``` r
tor::tor_example()
#> [1] "csv"   "mixed" "rdata" "rds"   "tsv"
fgeo.x::example_path()
#>  [1] "csv"           "mixed_files"   "rdata"         "rdata_one"    
#>  [5] "rds"           "taxa.csv"      "tsv"           "vft_4quad.csv"
#>  [9] "view"          "weird"         "xl"
tor::tor_example()
#> [1] "csv"   "mixed" "rdata" "rds"   "tsv"
```

<sup>Created on 2021-04-27 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

----

@AlexAxthelm, AFAIK, not in this package -- but it'd be great to hear from @MonikaFu

**Comment by cjyetman** [comment]
@maurolepore I don't think you're getting my point...

if you're listing **FILES**, it makes sense to give the user the path to the **FILE**

if you're listing **DATASETS**, it makes sense to give the user the **DATA**

**Comment by MonikaFu** [comment]
to be honest, I'm ok with leaving this discussion to you guys. No strong opinions here.

**Comment by cjyetman** [comment]
> Is there value in having datasets as raw files (`csv`, `xlsx`, etc.) and having vignettes walk through the entire process, import to results, or would that be best covered in `data_processing`?

I would assume no.... how you read in the data is completely irrelevant to this package.

**Comment by maurolepore** [comment]
@cjyetman, now I see your point -- thanks! Yeah, that's a great way to put it. 

Here is a weird edge case, just for curiosity, of function that reads all .rda in a directory. So the `example()` helper outputs a path to a directory, not a file:

``` r
(path_rda <- tor::tor_example("rdata"))
#> [1] "/home/mauro/R/x86_64-pc-linux-gnu-library/4.0/tor/extdata/rdata"
fs::is_dir(path_rda)
#> /home/mauro/R/x86_64-pc-linux-gnu-library/4.0/tor/extdata/rdata 
#>                                                            TRUE
fs::is_file(path_rda)
#> /home/mauro/R/x86_64-pc-linux-gnu-library/4.0/tor/extdata/rdata 
#>                                                           FALSE

tor::list_rdata(path_rda)
#> $rdata1
#> # A tibble: 2 x 1
#>       x
#>   <dbl>
#> 1     1
#> 2     2
#> 
#> $rdata2
#> # A tibble: 2 x 1
#>   y    
#>   <chr>
#> 1 a    
#> 2 b
```

<sup>Created on 2021-04-27 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

**Comment by AlexAxthelm** [comment]
I'm going to step in and call this one.

Let's go with the standard `data/` datasets, document them, and expose the data, not the paths to users. Since reading data isn't relevant to this package, let's stick to the standard structures.

A note for the future, maybe we can get the vignettes & examples in some of our other repos to have these examples as their end point, but that's a problem for the future.

@MonikaFu, are you the right person for this PR, since the bulk of the actual work will be documentation?

**Comment by MonikaFu** [comment]
@AlexAxthelm I think yes - maybe with some guidance from @maurolepore and @jdhoffa (I'm using example data from him).

**Comment by cjyetman** [comment]
> @cjyetman, now I see your point -- thanks! Yeah, that's a great way to put it.
> 
> Here is a weird edge case, just for curiosity, of function that reads all .rda in a directory. So the `example()` helper outputs a path to a directory, not a file:


I'm not familiar with the `tor` package, but looking at the DESCRIPTION of all 3 packages...

Package: readr
Title: Read Rectangular Text Data

Package: vroom
Title: Read and Write Rectangular Text Data Quickly

Package: tor
Title: Import Multiple Files From a Single Directory at Once

So all of them seem to be primarily focussed on reading in files. In that case, to me it makes sense that their "example data" is gonna be files, and in their example code their gonna want to use a path because that's likely going to be one of the parameters of their functions that they're demonstrating.

In contrast, if the functions in your package usually take a `data` parameter that accepts a data.frame or some other type of R object, you're probably gonna want to provide example data as R objects, i.e. as .rds files, and if you want to make it easy for users to use them and for example code to use them, either lazy load them when the package is attached, or create a function to return them by name as an object ready to go.

so your examples look like...
``` r
ex_data1 <- get_example(ex_data1)
my_func(data = ex_data1)
```

instead of...
``` r
ex_data1_path <- get_example(ex_data1)
exdata1 <- read.csv(ex_data1_path, stringsAsFactors = FALSE)
my_func(data = ex_data1)
```

**Comment by AlexAxthelm** [comment]
I think the syntax is even easier than that.

It would just be:
```r
my_func(data = ex_data1)
```

We don't do
```r
# Not valid code
mtcars < get_data("mtcars")
ggplot(mtcars, <aes, blah blah blah>)
```

with other datasets. So long as we maks sure to pick a name that doesn't conflict, it will be available in the global environment as soon as the package is loaded, or it can be called with `mypkg::my_dataset` otherwise.

**Comment by MonikaFu** [comment]
I believe that I put `sda_target` into that form already so it is a matter of changing the way `example_data` is called and also maybe changing the name to something better explaining what this data is.
